# Generated by Django 5.2.2 on 2025-06-08 20:50

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('tracking', models.URLField(blank=True)),
                ('repo', models.URLField(blank=True)),
                ('prototype', models.URLField(blank=True)),
                ('description', models.TextField(blank=True, max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('grade_1', models.FloatField(default=0)),
                ('grade_2', models.FloatField(default=0)),
                ('grade_avg', models.FloatField(default=0)),
                ('presences', models.IntegerField(default=0)),
                ('group', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='presence_count.group')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=100)),
                ('date', models.DateField(default=datetime.date.today)),
                ('description', models.TextField(blank=True, max_length=2048)),
                ('students', models.ManyToManyField(related_name='lesson_presence', to='presence_count.student')),
            ],
        ),
    ]
