# Generated by Django 4.2 on 2023-04-30 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presence_count', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='id',
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(default=None, max_length=100, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
