# Generated by Django 4.2 on 2023-04-30 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presence_count', '0002_remove_student_id_student_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='grade_1',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='student',
            name='grade_2',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='student',
            name='grade_avg',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='student',
            name='presences',
            field=models.IntegerField(default=0),
        ),
    ]
