# Generated by Django 4.2 on 2023-04-30 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presence_count', '0003_student_grade_1_student_grade_2_student_grade_avg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='grade_1',
            field=models.FloatField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='student',
            name='grade_2',
            field=models.FloatField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='student',
            name='grade_avg',
            field=models.FloatField(blank=True, default=None),
        ),
    ]
