# Generated by Django 4.2 on 2023-04-30 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presence_count', '0004_alter_student_grade_1_alter_student_grade_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='grade_1',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='grade_2',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='grade_avg',
            field=models.FloatField(default=0),
        ),
    ]
