# Generated by Django 4.2 on 2023-04-30 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presence_count', '0005_alter_student_grade_1_alter_student_grade_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='group',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
