# Generated by Django 4.2 on 2023-04-30 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presence_count', '0006_alter_student_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
