# Generated by Django 4.2 on 2023-04-30 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('presence_count', '0007_student_id_alter_student_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tracking', models.URLField()),
                ('repo', models.URLField()),
                ('prototype', models.URLField()),
                ('description', models.TextField(max_length=512)),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='group',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='presence_count.group'),
        ),
    ]
