# Generated by Django 4.2 on 2023-05-06 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('presence_count', '0008_group_alter_student_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='description',
            field=models.TextField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='group',
            name='prototype',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='repo',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='tracking',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='group',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='presence_count.group'),
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now=True)),
                ('description', models.TextField(blank=True, max_length=2048)),
                ('students', models.ManyToManyField(related_name='lesson_presence', to='presence_count.student')),
            ],
        ),
    ]
