# Generated by Django 4.2 on 2023-05-07 16:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presence_count', '0009_alter_group_description_alter_group_prototype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
